name: Continuous integration
on: push
defaults:
  run:
    shell: pwsh
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6
      - name: Build module
        id: build
        run: ./Build-Module.ps1
      - name: Analyze script
        id: analyze
        run: Invoke-ScriptAnalyzer *.psm1
      - name: Test module
        id: test
        run: |
          Import-Module ./*.psd1
          Invoke-Pester -Configuration @{TestResult=@{Enabled=$true}}
