name: Pester tests
on: push
defaults:
  run:
    shell: pwsh
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Build module
        id: build
        run: ./Build-Module.ps1
      - name: Test module
        id: test
        run: Import-Module ./*.psd1 ; Invoke-Pester
