name: Publish module to PowerShell Gallery
on:
  workflow_run:
    workflows: ["Continuous integration"]
    types: [completed]
    branches: [main]
jobs:
  publish:
    name: Publish to PowerShell Gallery
    runs-on: windows-latest
    steps:
      - name: Check out script source
        uses: actions/checkout@v6
      - name: Build module
        id: build
        run: ./Build-Module.ps1
      - name: Publish module
        id: publish
        env:
            GALLERYKEY: ${{ secrets.gallerykey }}
        run: Import-Module -Path ./src/*.psd1 -Force; Publish-Module ModernConveniences -NuGetApiKey $env:GALLERYKEY
